[package]
name = "first_cairo_tutorial"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.12.0"
alexandria_math = "0.6.0"

[dev-dependencies]
cairo_test = "2.12.0"

[executable]
# function = "first_cairo_tutorial::fibonacci::main"
function = "first_cairo_tutorial::functions::example"

# functions = [
#     "first_cairo_tutorial::fibonacci::main",
#     "first_cairo_tutorial::functions::example"
# ]